const FARM_TRANSLATIONS = {
  en: {
    "🌐 翻譯":"🌐 Translate","農場員工重要資訊公告":"Important Information for Farm Workers","請全體工作人員務必仔細閱讀並遵守以下規範":"All workers must read and follow the rules below carefully.",
    "@All 各位請注意：":"@All — Attention everyone:","請嚴格遵守農場守則，一旦被發現違規，可能會請你即時離场！":"Please follow all farm rules. If you are found breaking the rules, you may be required to leave the farm immediately.",
    "💰 工資和 Payslip 注意事項":"💰 Pay and Payslip Information","工資結算週期：":"Pay period:","星期四 至 下星期三 為一週。":"One pay week runs from Thursday to the following Wednesday.","工資及Payslip的發放時間：":"Pay and payslip issue time:","將於（結算週）的":"They will be issued by ","下週一,下午 17:00 前":"5:00 pm on the following Monday","發放完畢。":".","未收到工資及Payslip":"If you have not received your pay or payslip","(星期一,17:00後)":" (after 5:00 pm on Monday)","：如未收到工資和 payslip":"If you have not received your pay and payslip ","(先在垃圾郵件查核一下!!!再三告知先查核一下)":"(please check your spam/junk folder first)","，請務必於":" please notify management by ","週一晚上 19:00 分前":"7:00 pm on Monday","主動告知管理層。":".",
    "🚫 違規即時離場守則（請嚴格遵守）":"🚫 Rules That May Result in Immediate Removal (Strictly Enforced)","禁止坐桶：":"Do not sit on buckets:","大家不要坐桶子（農場的桶子只是用來採果,不是拿來坐!）。":"Farm buckets are for picking fruit only. Do not sit on them.","吸煙限制：":"Smoking restrictions:","嚴禁在場內吸煙（包括":"Smoking is strictly prohibited on the farm, including ","電子煙":"vaping/e-cigarettes","）。如需吸煙，請務必移步至場外指定區域。":". If you need to smoke, go to the designated area outside the farm.","交果洗手：":"Wash your hands after handing in fruit:","每次交果完畢後，請務必清洗雙手。":"Wash your hands every time after handing in your fruit.","場內禁食：":"No food in the work area:","場內禁止帶入食物及進食，(如帶了食物,請放在場外門口外)且":"Do not bring food into or eat in the work area. If you bring food, leave it outside the entrance. ","只允許飲用純水":"Only plain water is permitted","（禁止含糖飲料）。":"; sugary drinks are not allowed.","休息進食規範：":"Eating during breaks:","大家在休息時間如需進食，請至場外用餐。重新開始採果前，請務必洗手。":"If you eat during a break, please eat outside the work area. Wash your hands before you resume picking.","嚴禁隨地小便：":"No urinating or defecating on the farm:","請絕對不要在場內的草地上隨地大小二便。":"Do not urinate or defecate on the grass or anywhere in the farm area.","耳機配戴限制：":"Earphone restrictions:","如需配戴耳機，":"If you wear earphones, ","請只戴一邊":"use only one earbud","，以確保能聽到現場廣播或其他聲音（例如：叫大家交桶子）。":" so you can still hear announcements and instructions, such as calls to hand in buckets.","手套規格：":"Glove requirements:","嚴禁配戴不符合農場規格的手套（例如：不能使用完全覆蓋手指的手套，":"Do not wear gloves that do not meet farm requirements. Gloves must not fully cover your fingers; ","必須完全露出所有手指":"all fingers must remain fully exposed","）。":".","禁止戴太陽眼鏡：":"No sunglasses:","工作期間不能戴太陽眼鏡，以確保採收品質與眼睛能辨別顏色。":"Do not wear sunglasses while working, so colours can be seen accurately and picking quality can be maintained.","嚴禁損害農場利益：":"Do not damage farm property or interests:","嚴禁做出任何對農場造成風險損失的事情。例如：":"Do not do anything that may cause loss or damage to the farm. This includes ","偷竊":"theft","（包括藍莓及其他不屬於你的私人財產）、私自關掉農場水系統、破壞農場設備等。":" (including blueberries or other property that does not belong to you), turning off the farm water system without permission, or damaging farm equipment.",
    "🧺 農場採果規則":"🧺 Farm Picking Rules","不要選擇行數":"Do not choose your own row","，請按順序行數去採果。":"; pick the rows in the assigned order.","請 2 人為一組去採果，若只有 1 人，請變為 3 人一組（如有變更，會跟大家說）。":"Pick in pairs. If one person is left without a partner, form a group of three. You will be told if this arrangement changes.","在所有行數尚未完成之前，請不要偷採別人的行數的藍莓！":"Do not pick blueberries from another person's row while there are still unfinished rows.","若自己的那一行數已完成，請前往":"When you finish your row, move to a new row ","（同一區）":"in the same section","的新行數去採果。":" and continue picking.","若所有行數都已經有人正在採摘，你將會聽到「":"If every row is already being picked, wait until you hear “","」，才去幫其他人的行數去採果。":"” before helping in another person's row.","請聽從任何指示，包括採摘的行數及交桶。":"Follow all instructions, including which row to pick and when to hand in your bucket.","若有很多人需要洗手時，請禮貌排隊，不要插隊。":"If many people are waiting to wash their hands, please queue politely and do not cut in line.","‼️ 請各位保持和平，如有投訴，請跟管理層說，不要自行處理。":"‼️ Please remain respectful. If you have a complaint or concern, speak to management rather than handling it yourself.",
    "⚠️ 包裝注意事項":"⚠️ Packing Rules","在開工前（":"Begin preparing ","5分鐘":"5 minutes","）開始做準備工作。":" before your shift starts.","包裝前，請記得必須要用酒精搓手液。":"Use alcohol-based hand sanitiser before packing.","要戴包裝帽子（包好所有露出的頭髮）。":"Wear a packing hairnet/cap and make sure all hair is fully covered.","長頭髮的，必須綁起來。":"Long hair must be tied back.","手上（不能）戴任何飾物，包括手錶。":"Do not wear jewellery or a watch on your hands or wrists.","水瓶要放在休息室。":"Keep water bottles in the break room.","請專心工作，不要聊天，":"Stay focused on your work and avoid chatting. ","不能戴耳機及不要用手機‼️":"Do not wear earphones or use your phone while working. ‼️","如藍莓掉在地上，請馬上撿起來掉在垃圾桶。":"If blueberries fall on the floor, pick them up immediately and put them in the rubbish bin.","做完包裝，需立即做清潔（包括清洗機器及掃地）。":"After packing is finished, clean the work area immediately, including the machines and floor.",
    "📋 其他注意事項":"📋 Other Important Information","洗手間衛生問題：":"Toilet hygiene:","如果女生們需要更換生理用品，請用洗手間裡面的紙袋把用過的生理用品裝好，再掉進垃圾桶。":"If you need to change a sanitary product, place the used item in one of the paper bags provided in the toilet before putting it in the bin.","節能與整潔：":"Cleanliness and energy saving:","請各位保持洗手間清潔，和用完洗手間":"Please keep the toilet clean and ","必須關燈":"turn off the light after use","。":".","早上停車規範：":"Morning parking:","請大家早上":"In the morning, please ","不要把車停在洗手方這邊":"do not park near the hand-washing area","，因為開車門的聲音，會打擾到附近鄰居。":" because the sound of car doors may disturb nearby neighbours.","📸 洗手間告示（紙袋與關燈提示）":"📸 Toilet notice (paper bags and lights)","📸 外部告示（早上切勿在此停車）":"📸 Outdoor notice (no morning parking here)",
    "🍇 採果技巧與好壞果圖鑑":"🍇 Picking Tips and Blueberry Quality Guide","💡 腰帶使用規範":"💡 Using the Picking Belt","把藍莓桶連結腰帶上，盡量把它們拉緊，可以令腰部受力轉移到腳部。":"Attach the blueberry buckets securely to the belt and tighten it as much as comfortably possible. This helps distribute the load away from your lower back.","📸 腰帶綁法示範一":"📸 Belt setup example 1","📸 腰帶拉緊示範二":"📸 Belt setup example 2","🚛 交滿桶藍莓地方":"🚛 Where to Hand In Full Buckets","把自己滿藍莓的桶交到車上。":"Take your full blueberry bucket to the collection vehicle.","📸 交桶上車位置":"📸 Bucket hand-in point","✅ 好果標準":"✅ Good Fruit Standard","是全藍、沒有花、沒有樹枝、和沒有破皮膚的才是好果。":"Good blueberries should be fully blue, with no flowers, twigs, or damaged skin.","📸 標準好果示範一":"📸 Good fruit example 1","📸 標準好果示範二":"📸 Good fruit example 2","❌ 紅/綠果（嚴禁採摘）":"❌ Red/Green Fruit (Do Not Pick)","是不能採的，採摘會被警告！！！":"Do not pick red or green fruit. Picking it may result in a warning.","📸 不合格紅綠果一":"📸 Unripe fruit example 1","📸 不合格紅綠果二":"📸 Unripe fruit example 2","⚠️ 破皮果實處理":"⚠️ Damaged/Split Fruit","在採摘時如果有發現，請自行食了它解決。如果在桶內過多是會被警告！！在採摘時遇到容易破皮的，請用360度轉動方式採摘。":"If you find a split berry while picking, do not place it in your bucket. Too many damaged berries in your bucket may result in a warning. For berries that split easily, gently twist them 360 degrees when picking.","📸 破皮果實與採摘手法":"📸 Split fruit and picking technique","🚯 鼻屎果（小果）不摘":"🚯 Do Not Pick Very Small Berries","就是小到有如鼻屎的，自己都不會食的就不要摘了，可以直接跳過。":"If a berry is extremely small and you would not choose to eat it yourself, leave it on the plant and move on.","📸 鼻屎果大小對比":"📸 Very small berry size example","🍂 嚴禁掉果規範":"🍂 Do Not Drop Good Fruit on the Ground","禁止把好果掉在地上(除了壞果)":"Do not throw good fruit on the ground. Only genuinely bad fruit may be discarded there.","壞果/爛果定義：已經軟化，爆汁，蟲咬的果才可掉在地上。":"Bad/rotten fruit means berries that are soft, leaking juice, or damaged by insects.","（如經發現，會被警告，嚴重的人員會被停工及開除！）":"If this rule is breached, you may receive a warning. Serious breaches may result in suspension from work or termination.","📸 地面掉果不合格示範":"📸 Incorrect fruit disposal example","🌟 請大家做個好採手 🌟":"🌟 Please Be a Good Picker 🌟","👍 優秀土撥鼠採手榮譽榜":"👍 Good picker example",
    "🚜 常規農場工作守則":"🚜 General Farm Work Rules","請絕對聽從管理人員的合理指示。":"Follow all reasonable instructions given by management.","工作時間內需保持積極、認編的工作態度。":"Maintain a positive and responsible attitude while working.","請準時到達規定的農場（採果區域）集合，切勿遲到。":"Arrive on time at the designated farm/picking area. Do not be late.","成績與品質要求：":"Performance and quality requirements:","所有人的採收成績與品質均需盡量做到最好。成績欠佳或工作態度欠佳者，將面臨被停工及請離開的風險。":"Everyone is expected to maintain the best picking performance and quality they reasonably can. Poor performance or an unsatisfactory work attitude may result in suspension from work or being asked to leave.","📍 農場導航與介紹影片 (Farm Directory)":"📍 Farm Directions and Introduction Videos","澳洲":"Australia","🗺️ Google 導航地圖":"🗺️ Google Maps","🚙 Waze 導航":"🚙 Waze Navigation","▶️ 導航影片":"▶️ Directions Video","3. Ravensbourne Farm (經理場)":"3. Ravensbourne Farm (Manager's Farm)","請嚴格遵守農場守則 • 違規者將面臨即時離場處分":"Please follow all farm rules • Breaches may result in immediate removal from the work area"
  },
  "zh-CN": {
    "🌐 翻譯":"🌐 翻译","農場員工重要資訊公告":"农场员工重要信息公告","請全體工作人員務必仔細閱讀並遵守以下規範":"请所有工作人员务必仔细阅读并遵守以下规定","各位請注意":"各位请注意","請嚴格遵守農場守則":"请严格遵守农场规则","工資":"工资","發放":"发放","週":"周","請":"请","農場":"农场","採果":"采果","規則":"规则","嚴禁":"严禁","場內":"场内","藍莓":"蓝莓","包裝":"包装","注意事項":"注意事项","導航":"导航","影片":"视频","洗手間":"洗手间","關燈":"关灯","車":"车","經理場":"经理场","離場":"离场","開除":"解雇","員工":"员工","資訊":"信息","壞果":"坏果","爛果":"烂果","標準":"标准","紅/綠果":"红/绿果","採摘":"采摘","工作守則":"工作规则","管理層":"管理层","電子煙":"电子烟","太陽眼鏡":"太阳眼镜","週一":"周一","星期一":"星期一","下週一":"下周一","繁體中文":"繁体中文"
  },
  ja: {
    "🌐 翻譯":"🌐 翻訳","農場員工重要資訊公告":"農場スタッフへの重要なお知らせ","請全體工作人員務必仔細閱讀並遵守以下規範":"スタッフの皆さんは、以下のルールをよく読み、必ず守ってください。","💰 工資和 Payslip 注意事項":"💰 給与・給与明細について","🚫 違規即時離場守則（請嚴格遵守）":"🚫 違反時に即時退場となる場合があるルール（厳守）","🧺 農場採果規則":"🧺 農場での収穫ルール","⚠️ 包裝注意事項":"⚠️ パッキング作業の注意事項","📋 其他注意事項":"📋 その他の注意事項","🍇 採果技巧與好壞果圖鑑":"🍇 収穫のコツとブルーベリー品質ガイド","🚜 常規農場工作守則":"🚜 農場での基本作業ルール","📍 農場導航與介紹影片 (Farm Directory)":"📍 農場へのアクセス・案内動画","🗺️ Google 導航地圖":"🗺️ Google マップ","🚙 Waze 導航":"🚙 Waze ナビ","▶️ 導航影片":"▶️ 道順動画","請嚴格遵守農場守則 • 違規者將面臨即時離場處分":"農場のルールを必ず守ってください。違反した場合、直ちに退場を求められることがあります。"
  },
  ko: {
    "🌐 翻譯":"🌐 번역","農場員工重要資訊公告":"농장 근로자 중요 안내","請全體工作人員務必仔細閱讀並遵守以下規範":"모든 근로자는 아래 규정을 주의 깊게 읽고 반드시 준수해 주세요.","💰 工資和 Payslip 注意事項":"💰 급여 및 급여명세서 안내","🚫 違規即時離場守則（請嚴格遵守）":"🚫 위반 시 즉시 퇴장 조치될 수 있는 규정 (엄격 준수)","🧺 農場採果規則":"🧺 농장 수확 규정","⚠️ 包裝注意事項":"⚠️ 포장 작업 주의사항","📋 其他注意事項":"📋 기타 주의사항","🍇 採果技巧與好壞果圖鑑":"🍇 수확 요령 및 블루베리 품질 안내","🚜 常規農場工作守則":"🚜 기본 농장 작업 규정","📍 農場導航與介紹影片 (Farm Directory)":"📍 농장 길찾기 및 안내 영상","🗺️ Google 導航地圖":"🗺️ Google 지도","🚙 Waze 導航":"🚙 Waze 길찾기","▶️ 導航影片":"▶️ 길찾기 영상","請嚴格遵守農場守則 • 違規者將面臨即時離場處分":"농장 규정을 반드시 준수해 주세요. 위반 시 즉시 작업장에서 퇴장 조치될 수 있습니다."
  }
};

const FARM_ORIGINAL_TEXT = new WeakMap();

function applyFarmLanguage(language) {
  const map = FARM_TRANSLATIONS[language];
  document.documentElement.lang = language === 'zh-TW' ? 'zh-HK' : language;
  const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
  const nodes = [];
  while (walker.nextNode()) nodes.push(walker.currentNode);
  for (const node of nodes) {
    if (node.parentElement && ['SCRIPT','STYLE'].includes(node.parentElement.tagName)) continue;
    if (!FARM_ORIGINAL_TEXT.has(node)) FARM_ORIGINAL_TEXT.set(node, node.nodeValue);
    const original = FARM_ORIGINAL_TEXT.get(node);
    if (language === 'zh-TW') { node.nodeValue = original; continue; }
    let value = original;
    const exact = map && map[value.trim()];
    if (exact !== undefined) {
      const lead = value.match(/^\s*/)[0], tail = value.match(/\s*$/)[0];
      node.nodeValue = lead + exact + tail;
      continue;
    }
    if (map) {
      for (const [from,to] of Object.entries(map)) {
        if (from.length >= 2 && value.includes(from)) value = value.split(from).join(to);
      }
    }
    node.nodeValue = value;
  }
  localStorage.setItem('farmLanguage', language);
}
